language: objective-c

before_install:
  - brew update
  - brew install python
  - brew install python3
  - brew install valgrind
  - git submodule update --init --recursive
  - make test
  - pip install coverage coveralls
  - python setup.py install

script:
  - DYLD_LIBRARY_PATH=libtap ./test
  - python tests/test.py
  
after_success:
  - coveralls --exclude test.c --exclude chizer.h --exclude data --exclude libtap --gcov-options '\-lp'
  - make clean
  - make chizer
  - time cxx/chizer data/ac59ab5a282afd3de22062c7d62b5367
  - DYLD_LIBRARY_PATH=libtap G_SLICE=always-malloc G_DEBUG=gc-friendly  valgrind -v --tool=memcheck --leak-check=full --show-reachable=yes --log-file=a.log --num-callers=40 cxx/chizer data/ac59ab5a282afd3de22062c7d62b5367
  - cat a.log
