language: c
compiler: gcc

before_install:
  - git submodule update --init --recursive
  - make test
  - make python
  - sudo pip install cpp-coveralls
script:
  - ./test
  - python test.py
after_success:
  - coveralls --exclude test.c --exclude chizer.h --exclude data --exclude libtap --gcov-options '\-lp'
  - make clean
  - make chizer
  - time ./chizer data/ac59ab5a282afd3de22062c7d62b5367
